# Generated by Django 2.2.12 on 2020-12-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='Video_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
